source 'https://github.com/CocoaPods/Specs.git'

target :Stopwatch do
  platform :ios, '8.0'
  pod 'Appboy-iOS-SDK'
  pod 'NUI',:git => 'https://github.com/tombenner/nui.git'
  pod 'KKColorListPicker', :git => 'https://github.com/leoru/KKColorListPicker.git'
  pod 'CrittercismSDK'
  pod 'Firebase/DynamicLinks'
  pod 'Branch'
end
